name: actions-config

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: psql -f storage/init.sql -U postgres
      - run: PGPASSWORD=venus psql -d dcs -f storage/tables.sql -U venus
      - run: PGPASSWORD=venus psql -d dcs -f storage/data.sql -U venus
      - name: tests
        run: npm test
