name: actions-config

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node:
          - 12
          - 14
        os:
          - ubuntu-latest

    services:
      postgres:
        image: postgres:11.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: db_test
        ports:
          - 5432/tcp
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
      - name: Connect to PostgreSQL
      # Runs a script that creates a PostgreSQL client, populates
      # the client with data, and retrieves data
        run: node client.js
      # Environment variable used by the `client.js` script to create a new PostgreSQL client.
        env:
        # The hostname used to communicate with the PostgreSQL service container
          POSTGRES_HOST: postgres
        # The default PostgreSQL port
          POSTGRES_PORT: 5432
      - run: npm test
