on:
    push:
        branches:
          - main
          - dev
          - pg-container


jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm ci
      - uses: harmon758/postgresql-action@v1
        with:
          postgresql db: 'dcs'
          postgresql user: 'venus'
          postgresql password: 'venus'

      - name: Tests
        run: npm test
